#!/bin/bash
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
cp local_settings_template.py local_settings.py
./manage.py syncdb --noinput
./manage.py migrate
./manage.py createsuperuser